language: node_js
node_js:
  - "8"
  - "lts/*"
install:
  - npm install
  - npm install -g codecov
script:
  - npm test 
  - NODE_ENV=test nyc --report-dir=coverage/reporter --reporter=lcov-only node tests/jasmine.runner.js
  - karma start karma.conf.js --cc=true
  - codecov
